#!/usr/bin/python3

import socket
import sys

def start_server(port: int = 7000):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        sock.bind(("0.0.0.0", port))
    except PermissionError:
        print("[!] No permission opening port: {}".format(port))

    pass

def parse_argument() -> int:
    port = 0
    if len(sys.argv) < 2:
        print("Usage: {} <port>".format(sys.argv[0]))
        exit(1)
    try:
        port = int(sys.argv[1])
    except ValueError:
        print("[!] Invalid port number")
        exit(1)
    return port

def main():
    port = parse_argument()
    start_server(port=port)
    pass

if __name__ == "__main__":
    main()
